states_abb = [ 'AK', 'AL', 'AR', 'AZ', 'CA', 'CO', 'CT', 'DE', 'FL', 'GA', 'HI', 
               'IA', 'ID', 'IL', 'IN', 'KS', 'KY', 'LA', 'MA', 'MD', 'ME', 'MI',
               'MN', 'MO', 'MS', 'MT', 'NC', 'ND', 'NE', 'NH', 'NJ', 'NM', 'NV', 
               'NY', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX', 'UT', 
               'VA', 'VT', 'WA', 'WI', 'WV', 'WY', 'AS', 'DC', 'GU', 'MP', 'PR', 
               'UM', 'VI']

street_abbrev = ["ALY", "ANX", "ARC", "AVE", "YU", "BCH", "BND", "BLF", "BTM", "BLVD", "BR", "BRG", "BRK", "BG", "BYP", "CP", "CYN", "CPE", "CSWY", "CTR", "CIR", "CLFS", "CLB", "COR", "CORS", "CRSE", "CT", "CTS", "CV", "CRK", "CRES", "XING", "DL", "DM", "DV", "DR", "EST", "EXPY", "EXT", "FALL", "FLS", "FRY", "FLD", "FLDS", "FLT", "FOR", "FRST", "FGR", "FORK", "FRKS", "FT", "FWY", "GDNS", "GTWY", "GLN", "GN", "GRV", "HBR", "HVN", "HTS", "HWY", "HL", "HLS", "HOLW", "INLT", "IS", "ISS", "ISLE", "JCT", "CY", "KNLS", "LK", "LKS", "LNDG", "LN", "LGT", "LF", "LCKS", "LDG", "LOOP", "MALL", "MNR", "MDWS", "ML", "MLS", "MSN", "MT", "MTN", "NCK", "ORCH", "OVAL", "PARK", "PKY", "PASS", "PATH", "PIKE", "PNES", "PL", "PLN", "PLNS", "PLZ", "PT", "PRT", "PR", "RADL", "RNCH", "RPDS", "RST", "RDG", "RIV", "RD", "ROW", "RUN", "SHL", "SHLS", "SHR", "SHRS", "SPG",  "SPGS", "SPUR", "SQ", "STA", "STRA", "STRM", "ST", "SMT", "TER", "TRCE", "TRAK", "TRL", "TRLR", "TUNL", "TPKE", "UN", "VLY", "VIA", "VW", "VLG", "VL", "VIS", 
"WALK", "WAY", "WLS"]

find_state = {
        "Alabama": "AL",
        "Alaska": "AK",
        "Arizona": "AZ",
        "Arkansas": "AR",
        "California": "CA",
        "Colorado": "CO",
        "Connecticut": "CT",
        "Delaware": "DE",
        "Florida": "FL",
        "Georgia": "GA",
        "Hawaii": "HI",
        "Idaho": "ID",
        "Illinois": "IL",
        "Indiana": "IN",
        "Iowa": "IA",
        "Kansas": "KS",
        "Kentucky": "KY",
        "Louisiana": "LA",
        "Maine": "ME",
        "Maryland": "MD",
        "Massachusetts": "MA",
        "Michigan": "MI",
        "Minnesota": "MN",
        "Mississippi": "MS",
        "Missouri": "MO",
        "Montana": "MT",
        "Nebraska": "NE",
        "Nevada": "NV",
        "New Hampshire": "NH",
        "New Jersey": "NJ",
        "New Mexico": "NM",
        "New York": "NY",
        "North Carolina": "NC",
        "North Dakota": "ND",
        "Ohio": "OH",
        "Oklahoma": "OK",
        "Oregon": "OR",
        "Pennsylvania": "PA",
        "Rhode Island": "RI",
        "South Carolina": "SC",
        "South Dakota": "SD",
        "Tennessee": "TN",
        "Texas": "TX",
        "Utah": "UT",
        "Vermont": "VT",
        "Virginia": "VA",
        "Washington": "WA",
        "West Virginia": "WV",
        "Wisconsin": "WI",
        "Wyoming": "WY",
        "District of Columbia": "DC",
        "American Samoa": "AS",
        "Guam": "GU",
        "Northern Mariana Islands": "MP",
        "Puerto Rico": "PR",
        "United States Minor Outlying Islands": "UM",
        "U.S. Virgin Islands": "VI",
}

street_name_abbrev= {
        "Alley":  "ALY",
        "Annex":  "ANX",
        "Arcade":  "ARC",
        "Avenue":  "AVE",
        "Bayou":  "YU",
        "Beach":  "BCH",
        "Bend":  "BND",
        "Bluff":  "BLF",
        "Bottom":  "BTM",
        "Boulevard":  "BLVD",
        "Branch":  "BR",
        "Bridge":  "BRG",
        "Brook":  "BRK",
        "Burg":  "BG",
        "Bypass":  "BYP",
        "Camp":  "CP",
        "Canyon":  "CYN",
        "Cape":  "CPE",
        "Causeway":  "CSWY",
        "Center":  "CTR",
        "Circle":  "CIR",
        "Cliffs":  "CLFS",
        "Club":  "CLB",
        "Corner":  "COR",
        "Corners":  "CORS",
        "Course":  "CRSE",
        "Court":  "CT",
        "Courts":  "CTS",
        "Cove":  "CV",
        "Creek":  "CRK",
        "Crescent":  "CRES",
        "Crossing":  "XING",
        "Dale":  "DL",
        "Dam":  "DM",
        "Divide":  "DV",
        "Drive":  "DR",
        "Estates":  "EST",
        "Expressway":  "EXPY",
        "Extension":  "EXT",
        "Fall":  "FALL",
        "Falls":  "FLS",
        "Ferry":  "FRY",
        "Field":  "FLD",
        "Fields":  "FLDS",
        "Flats":  "FLT",
        "Ford":  "FOR",
        "Forest":  "FRST",
        "Forge":  "FGR",
        "Fork":  "FORK",
        "Forks":  "FRKS",
        "Fort":  "FT",
        "Freeway":  "FWY",
        "Gardens":  "GDNS",
        "Gateway":  "GTWY",
        "Glen":  "GLN",
        "Green":  "GN",
        "Grove":  "GRV",
        "Harbor":  "HBR",
        "Haven":  "HVN",
        "Heights":  "HTS",
        "Highway":  "HWY",
        "Hill":  "HL",
        "Hills":  "HLS",
        "Hollow":  "HOLW",
        "Inlet":  "INLT",
        "Island":  "IS",
        "Islands":  "ISS",
        "Isle":  "ISLE",
        "Junction":  "JCT",
        "Key":  "CY",
        "Knolls":  "KNLS",
        "Lake":  "LK",
        "Lakes":  "LKS",
        "Landing":  "LNDG",
        "Lane":  "LN",
        "Light":  "LGT",
        "Loaf":  "LF",
        "Locks":  "LCKS",
        "Lodge":  "LDG",
        "Loop":  "LOOP",
        "Mall":  "MALL",
        "Manor":  "MNR",
        "Meadows":  "MDWS",
        "Mill":  "ML",
        "Mills":  "MLS",
        "Mission":  "MSN",
        "Mount":  "MT",
        "Mountain":  "MTN",
        "Neck":  "NCK",
        "Orchard":  "ORCH",
        "Oval":  "OVAL",
        "Park":  "PARK",
        "Parkway":  "PKY",
        "Pass":  "PASS",
        "Path":  "PATH",
        "Pike":  "PIKE",
        "Pines":  "PNES",
        "Place":  "PL",
        "Plain":  "PLN",
        "Plains":  "PLNS",
        "Plaza":  "PLZ",
        "Point":  "PT",
        "Port":  "PRT",
        "Prairie":  "PR",
        "Radial":  "RADL",
        "Ranch":  "RNCH",
        "Rapids":  "RPDS",
        "Rest":  "RST",
        "Ridge":  "RDG",
        "River":  "RIV",
        "Road":  "RD",
        "Row":  "ROW",
        "Run":  "RUN",
        "Shoal":  "SHL",
        "Shoals":  "SHLS",
        "Shore":  "SHR",
        "Shores":  "SHRS",
        "Spring":  "SPG",
        "Springs":  "SPGS",
        "Spur":  "SPUR",
        "Square":  "SQ",
        "Station":  "STA",
        "Stravenues":  "STRA",
        "Stream":  "STRM",
        "Street":  "ST",
        "Summit":  "SMT",
        "Terrace":  "TER",
        "Trace":  "TRCE",
        "Track":  "TRAK",
        "Trail":  "TRL",
        "Trailer":  "TRLR",
        "Tunnel":  "TUNL",
        "Turnpike":  "TPKE",
        "Union":  "UN",
        "Valley":  "VLY",
        "Viaduct":  "VIA",
        "View":	 "VW",
        "Village":	"VLG",
        "Ville":  "VL",
        "Vista":  "VIS",
        "Walk":	 "WALK",
        "Way":  "WAY",
        "Wells":  "WLS",
    }